version: "3.7"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1024 # The user ID of the current user
      - PGID=100 # The group ID of the current user
      - TZ=Europe/Amsterdam # The Timezone where you live
    volumes:
      - /volume1/docker/config/Tautulli:/config
    ports:
      - 8181:8181 # The port on which you can access this service
    restart: unless-stopped
